/*
 * Copyright (C) 2016
 * 
 * 
 * 
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package edu.wright.cs.sp16.ceg3120;

import java.awt.Choice;
import java.awt.Font;

import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;

/**
 * This class is created to display the profile window which contains the
 * connections and the user preferences. The user will set the default database,
 * default view, default encoding, table view, and remember any few number of
 * last queries.
 */
public class Profile extends JFrame {
	
	

	/**
	 * generic static final long serialVersionUID.
	 */
	private static final long serialVersionUID = 3936531799918625132L;
	
	

	// Components of window declaration - do not modify
	private Choice choice1;
	private Choice choice2;
	private Choice choice3;
	private JLabel defaultEncoding;
	private JLabel defaultFavorite;
	private JLabel defaultView;
	private JMenu editMenu;
	private JMenu fileMenu;
	private JCheckBox gridLines;
	private JMenu helpMenu;
	private JMenuBar jmenuBar1;
	private JPanel jpanel1;
	private JPanel jpanel2;
	private JTabbedPane otherConnection;
	private JComboBox<NumberOfQueries> pxQueries;
	private JLabel queries;
	private JLabel rememberLast;
	private JCheckBox startupConnect;
	private JCheckBox startupMotd;
	private JLabel tableViews;
	private JCheckBox useMonospaced;
	private JMenu windowMenu;
	// End of variables declaration
	
	

	/**
	 * Constructor with zero-arguments to open the connection window.
	 */
	public Profile() {
		super("Connection");
		setResizable(false);
		setLocationRelativeTo(null);

		// This method is created by GUI Builder to customize how the window
		// will look like ,,,
		initComponents();
	} // End of Constructor method ,,,
	
	

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings({ "unchecked", "rawtypes" })
	private void initComponents() {

		// Initializing components of the window ,,,
		otherConnection = new JTabbedPane();
		jpanel1 = new JPanel();
		jpanel2 = new JPanel();
		defaultFavorite = new JLabel();
		defaultView = new JLabel();
		defaultEncoding = new JLabel();
		tableViews = new JLabel();
		rememberLast = new JLabel();
		choice1 = new Choice();
		choice2 = new Choice();
		choice3 = new Choice();
		startupConnect = new JCheckBox();
		startupMotd = new JCheckBox();
		useMonospaced = new JCheckBox();
		gridLines = new JCheckBox();
		pxQueries = new JComboBox<NumberOfQueries>();
		queries = new JLabel();
		jmenuBar1 = new JMenuBar();
		fileMenu = new JMenu();
		editMenu = new JMenu();
		windowMenu = new JMenu();
		helpMenu = new JMenu();
		
		// End of initializing components ,,,
		

		/**
		 * This block of code was generated by GUI Builder to set the components
		 * of the window and place them in the desired order. It also has the
		 * naming of the components.
		 */
		GroupLayout jpanel1Layout = new GroupLayout(jpanel1);
		jpanel1.setLayout(jpanel1Layout);
		jpanel1Layout.setHorizontalGroup(jpanel1Layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addGap(0, 494, Short.MAX_VALUE));
		jpanel1Layout.setVerticalGroup(jpanel1Layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addGap(0, 269, Short.MAX_VALUE));

		otherConnection.addTab("Connection 1", jpanel1);

		defaultFavorite.setText("Default Database:");

		defaultView.setText("Default View:");

		defaultEncoding.setText("Default Encoding:");

		tableViews.setText("Table Views:");

		rememberLast.setText("Remember Last:");

		startupConnect.setFont(new Font("Lucida Grande", 0, 11)); // NOI18N
		startupConnect.setText("Connect to Default on Startup");

		startupMotd.setFont(new Font("Lucida Grande", 0, 11)); // NOI18N
		startupMotd.setText("\"Message of the Day\" on Startup");

		useMonospaced.setFont(new Font("Lucida Grande", 0, 11)); // NOI18N
		useMonospaced.setText("Use monospaced fonts");

		gridLines.setFont(new Font("Lucida Grande", 0, 11)); // NOI18N
		gridLines.setText("Display vertical grid lines");

		pxQueries.setModel(new DefaultComboBoxModel(new NumberOfQueries[] {
				NumberOfQueries.Zero, NumberOfQueries.Five,
				NumberOfQueries.Ten, NumberOfQueries.Twenty }));

		queries.setText("queries");

		GroupLayout jpanel2Layout = new GroupLayout(jpanel2);
		jpanel2.setLayout(jpanel2Layout);
		jpanel2Layout
				.setHorizontalGroup(jpanel2Layout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(
								jpanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jpanel2Layout
														.createParallelGroup(
																GroupLayout.Alignment.LEADING)
														.addComponent(
																defaultFavorite)
														.addComponent(
																defaultEncoding)
														.addComponent(
																defaultView)
														.addComponent(
																tableViews)
														.addComponent(
																rememberLast))
										.addGap(59, 59, 59)
										.addGroup(
												jpanel2Layout
														.createParallelGroup(
																GroupLayout.Alignment.LEADING)
														.addGroup(
																jpanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				pxQueries,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				queries))
														.addComponent(
																useMonospaced)
														.addComponent(
																choice3,
																GroupLayout.PREFERRED_SIZE,
																166,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																choice2,
																GroupLayout.PREFERRED_SIZE,
																166,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																choice1,
																GroupLayout.PREFERRED_SIZE,
																166,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																startupConnect)
														.addComponent(
																startupMotd)
														.addComponent(gridLines))
										.addContainerGap(
												GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jpanel2Layout
				.setVerticalGroup(jpanel2Layout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(
								jpanel2Layout
										.createSequentialGroup()
										.addGap(20, 20, 20)
										.addGroup(
												jpanel2Layout
														.createParallelGroup(
																GroupLayout.Alignment.LEADING)
														.addComponent(
																defaultFavorite)
														.addComponent(
																choice1,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(2, 2, 2)
										.addComponent(startupConnect)
										.addGap(3, 3, 3)
										.addComponent(startupMotd)
										.addPreferredGap(
												LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jpanel2Layout
														.createParallelGroup(
																GroupLayout.Alignment.LEADING)
														.addComponent(
																defaultView)
														.addComponent(
																choice3,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jpanel2Layout
														.createParallelGroup(
																GroupLayout.Alignment.LEADING)
														.addComponent(
																defaultEncoding)
														.addComponent(
																choice2,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jpanel2Layout
														.createParallelGroup(
																GroupLayout.Alignment.LEADING)
														.addGroup(
																jpanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				useMonospaced)
																		.addPreferredGap(
																				LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				gridLines))
														.addComponent(
																tableViews))
										.addPreferredGap(
												LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jpanel2Layout
														.createParallelGroup(
																GroupLayout.Alignment.LEADING)
														.addComponent(
																rememberLast)
														.addGroup(
																jpanel2Layout
																		.createParallelGroup(
																				GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				pxQueries,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				queries)))
										.addContainerGap(33, Short.MAX_VALUE)));

		otherConnection.addTab("User Preferences", jpanel2);

		fileMenu.setText("File");
		jmenuBar1.add(fileMenu);

		editMenu.setText("Edit");
		jmenuBar1.add(editMenu);

		windowMenu.setText("Window");
		jmenuBar1.add(windowMenu);

		helpMenu.setText("Help");
		jmenuBar1.add(helpMenu);

		setJMenuBar(jmenuBar1);

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addComponent(otherConnection));
		layout.setVerticalGroup(layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addGroup(
				GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addComponent(otherConnection)
						.addContainerGap()));

		// This is to close the window when the 'X' button is clicked ,,,
		setDefaultCloseOperation(EXIT_ON_CLOSE);

		// This is to view the window after it is constructed ,,,
		setVisible(true);

		// This is to control the size and boundaries of the window after it is
		// constructed ,,,
		pack();
	} // End of initComponents method ,,,

} // End of Profile class ,,,


